### ISSUE TITLE
reading answers 

### ISSUE THREAD

**Issue by someoneyoudontknow22** [TheLazySquid/GimkitCheat#1]
idk why but it says Uncaught TypeError: Cannot read properties of undefined (reading 'answers')

**Comment by someoneyoudontknow22** [comment]
i  fixed it but it doesnt move the questions to bottom right and it doesnt  turn them green

**Comment by TheLazySquid** [comment]
> i fixed it but it doesnt move the questions to bottom right and it doesnt turn them green

Did you manually answer all the questions first? You need to do that once in order for the script to start coloring things in/moving the correct answer.
