### ISSUE TITLE
Tag!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#10]
**What feature would you like added?**
PLs add tag it would be cool 
**How difficult do you think it would be to implement?**
Not hard at all since you have ctf

**Comment by TheLazySquid** [comment]
There's now a basic script for tag available [here](https://github.com/TheLazySquid/GimkitCheat/blob/main/gamemodes/tag.js)! There's definitely more to come, as this one is pretty bare-bones.
