### ISSUE TITLE
Could it be possible to add snow brawl 

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#11]
**What feature would you like added?**
Snowbrawl and you can hit people through walls like one way out.
**How difficult do you think it would be to implement?**
Pretty hard I think its ok if you cant do it.

**Comment by TheLazySquid** [comment]
This has now been added, try it out [here](https://github.com/TheLazySquid/GimkitCheat/blob/main/gamemodes/snowbrawl.js)!
