### ISSUE TITLE
Pls guys don't share this with people I dont want it to start getting known then gimkit makes a fix like all the other ones

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#12]
You have the only working ones

**Comment by TheLazySquid** [comment]
This script has something that Gimkit really can't fix without making a proper anti-cheat, that being the local override. However, making something like that would probably be too large an undertaking to Gimkit to do any time soon, so I don't think these scripts will get fixed for at least a while.
