### ISSUE TITLE
This would a game changer

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#13]
**What feature would you like added?**
Refy a settings bar were you could make keybinds for certian hacks
**How difficult do you think it would be to implement?**
Super hard but would be very rewarding

**Comment by PierceMichael** [comment]
i don't think it would be that hard just need to add a event key listener to activate/deactivate

**Comment by CalebHacks** [comment]
I would be veruy good though

**Comment by TheLazySquid** [comment]
Just added this in, let me know if anything doesn't work.
