### ISSUE TITLE
hightlight other player

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#16]
**Describe the bug**
What is the bug? What does it affect?
THe highlighting of other players did not work in tag or snowbrawl or any of the game modes that I know of
**To Reproduce**
What browser are you using?
Crome
What error messages are in the console? (If any)
VM85:36 Uncaught TypeError: gc.getUser is not a function
    at <anonymous>:36:23
    at e.patch (App.4382044d.js:3878:21)
    at e.onMessageCallback (App.4382044d.js:3855:26)
What were you doing when the bug occurred?
I am trying to highlight the other players
**Additional context**
In which modes should it work?

**Comment by TheLazySquid** [comment]
I can't test this right now, but try updating the Override. The highlighter uses a function I only recently added, and I may have messed up the auto updater

**Comment by RONAKPATELLLLLLL** [comment]
ok
