### ISSUE TITLE
Gimkit Gims

### ISSUE THREAD

**Issue by PierceMichael** [TheLazySquid/GimkitCheat#18]
**What feature would you like added?**
The ability to use any Gim/Skin
**How difficult do you think it would be to implement?**
Pretty Hard more likely. If it's anything like blooket blooks then it would be complicated.

**Comment by CalebHacks** [comment]
That sounds reallly cool

**Comment by PierceMichael** [comment]
I'm mainly wanting it since certain gims aren't available anymore

**Comment by RONAKPATELLLLLLL** [comment]
That sounds like a good idea

**Comment by TheLazySquid** [comment]
Unfortunately, I can't find a way to purchase/equip cosmetics that you don't own and can't buy. I could potentially make it work client-side, but nobody else would be able to see the gim you chose. Give me a bit to experiment

**Comment by PierceMichael** [comment]
ok its fine if you can't figure it out

**Comment by PierceMichael** [comment]
> i don't know much about gimkit, though i do know enough about limitations to know this direct thing probably isn't possible. i know that at least normal games, if not 2d, use react, and so you may be able to modify a react variable? either way i feel that you could make an xp flooder (again idk about gimkit)

an xp flooder would be nice

**Comment by RONAKPATELLLLLLL** [comment]
Yeah that would be nice.

**Comment by TheLazySquid** [comment]
Here's the script for the cosmetic picker! [cosmeticpicker.js](https://github.com/TheLazySquid/GimkitCheat/blob/main/general/cosmeticpicker.js) Do note that you'll need to download a new override to use it, this one overrides what I think is some sort of character manager.
