### ISSUE TITLE
Cheat stopped working

### ISSUE THREAD

**Issue by moonidk** [TheLazySquid/GimkitCheat#2]
The script no longer works for me.

**Comment by TheLazySquid** [comment]
Hey! 

Could you be a little more specific with the issue you've been having? Did you:
A) Get the popup confirming whether you wanted to recolor buttons?
B) Answer all the questions in the kit once?
And if you did both those things, it would also be helpful to know what error the script ran in to (if any). If you open up the inspector console, find the error that looks like this one:
![errorExample](https://user-images.githubusercontent.com/76746384/204533434-6f70fc52-839b-4a24-b1b7-9f30d48851a6.png)
The `debugger eval code` part is browser-specific, but it shouldn't be hard to find the one that the script threw (it's usually at the bottom anyways).

Thanks!
