### ISSUE TITLE
Auto attack

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#23]
**Describe the bug**
What is the bug? What does it affect?
One Way Out
**To Reproduce**
What browser are you using?
Crome
What error messages are in the console? (If any)

What were you doing when the bug occurred?

**Additional context**
Add any other context about the problem here
Can you fix the auto attack or is it permanently patched

**Comment by TheLazySquid** [comment]
Unfortunately, probably not. The way it used to work was pretending that the projectile was fired from directly on top of the enemy, but Gimkit now has a check for whether the projectile is getting fired from within like 100px of you, so it doesn't work unless you're directly on top of an enemy.
