### ISSUE TITLE
Snowy Survial

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#25]
**What feature would you like added?**
The ability to buy the med and shield from anywhere 
**How difficult do you think it would be to implement?**
Very easy because you can copy it from the one-way-out and the snowbrawl

**Comment by RONAKPATELLLLLLL** [comment]
PLZ?

**Comment by TheLazySquid** [comment]
As far as I can tell, there aren't actually any shield cans/medpacks in Snowy Survival
