### ISSUE TITLE
skid report

### ISSUE THREAD

**Issue by VillainsRule** [TheLazySquid/GimkitCheat#28]
once you become a large hack maker, you get skidded off.
you need to create a license that essentially prevents people from redistributing the code.
without this, you basically cant do shit.
with this, you can send dmca requests to all the little skids and get their stuff taken down!!

here's the skid: https://github.com/r3a1ty/Gimkit-Hack-23-24

**Comment by TheLazySquid** [comment]
Thanks for reporting this, completely forgot that I'd need to do something like that. Do you know what license would be the best in this situation? I don't have any real experience with this sort of thing

**Comment by PierceMichael** [comment]
> Thanks for reporting this, completely forgot that I'd need to do something like that. Do you know what license would be the best in this situation? I don't have any real experience with this sort of thing

I think you could do The Unlicense?
