### ISSUE TITLE
GameModes

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#30]
Will there be more cheats for other game modes soon, or is these all the cheats you can make?
Thank you

**Comment by TheLazySquid** [comment]
Aside from non-2d gamemodes (which I rarely play), this is really everything I can think of in terms of cheats. What I have in the works right now is some kind of bot system, but right now that's only half done. As always, if you have any ideas, feel free to open an issue asking about them.

**Comment by RONAKPATELLLLLLL** [comment]
ok thanks
