### ISSUE TITLE
I got some ideas

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#31]
Fishtopia
Sell fish without being at the sell station and fish anywhere without being on the water, after using a "travel to..." thing you will be able to always use it from anywhere.
One Way Out
 you can purchase health, shield, bridges, and checkpoints from anywhere.
Farmchain
get water, research, seeds, and unlocks from anywhere.  an "auto harvest" mode which will automatically collect grown crops from wherever, and an auto plant mode. Auto plant mode automatically will plant seeds.
Capture the Flag
 allows you to purchase upgrades and invisabits from anywhere.
SnowBrawl
This script allows you to buy health and med packs from anywhere.

**Comment by TheLazySquid** [comment]
Unfortunately, literally all of that got patched out by Gimkit recently (which is why it's not in the new version)

**Comment by RONAKPATELLLLLLL** [comment]
oh, ok, sorry.

**Comment by sealldeveloper** [comment]
I could still sell fish without being at the station using Burp Suite intercepts of websockets, you just have to be in the same 'world' (eg, cant fish at purple unless your at purple, or use the sell table unless your in that world), but an option to start a Fish or Sell in that world at any point would be sick, and save travel time (esp for something like cosmic). 

Also Auto-fish for the fishing mode would save the process of manually clicking 'Fish Again'.

**Comment by TheLazySquid** [comment]
I tried recreating what you said, but it looks to me like you can only use the sell table or fish when very near to the device that initiates it. Could you provide more info on how you managed it?

From my testing I can sell here
![image](https://github.com/TheLazySquid/GimkitCheat/assets/76746384/8d6c8e48-84f5-48a4-8227-c2080609e727)

But not from here
![image](https://github.com/TheLazySquid/GimkitCheat/assets/76746384/fadc7d1a-181f-4bb5-99a8-2311cd415d5d)
