### ISSUE TITLE
Extensionless

### ISSUE THREAD

**Issue by asdcf35** [TheLazySquid/GimkitCheat#34]
It is very good, but could you make it without tampermonkey?

**Comment by TheLazySquid** [comment]
Unfortunately, this code needs to be run before any of Gimkit's scripts load in. This requires using something like Tampermonkey to inject it. [an old version](https://github.com/TheLazySquid/GimkitCheat/blob/main/oldVersions/v1/general.js) can be run purely in the console, but it requires answering every question in a kit and isn't maintained.

**Comment by TheLazySquid** [comment]
Update: there's now an experimental version that includes both a version you can copy into the console and a bookmarket [here](https://github.com/TheLazySquid/GimkitCheat/tree/v4).
