### ISSUE TITLE
Add a option to put a random amount of time (10-15 seconds) between auto answering.

### ISSUE THREAD

**Issue by pagedpenguin251** [TheLazySquid/GimkitCheat#35]
It is almost imposable to not get flagged as cheating and not be able to collect xp which was very useful when it worked this would fix that.

**Comment by TheLazySquid** [comment]
Hey! From my experience, the rate that I've chosen (one answer a second) doesn't lead to being flagged. I'll do some more testing later today to check if they've changed this.

**Comment by TheLazySquid** [comment]
I just ran it for around half an hour, and I didn't get kicked. Have you seen it cause you to be kicked firsthand?

**Comment by pagedpenguin251** [comment]
I have not been kicked but it stopped giving me XP after about 15 questions and my XP wasn't maxed out.

**Comment by pagedpenguin251** [comment]
Just did some testing and I realized that I wasn't getting xp because I was hosting on the same account as I was playing on. When I hosted t on a different account it worked
