### ISSUE TITLE
Add Option in the GUI to hide the "+1000 energy" popup.

### ISSUE THREAD

**Issue by pagedpenguin251** [TheLazySquid/GimkitCheat#37]
What feature would you like added?
Option in the GUI to hide the "+1000 energy" popup in game modes that use energy to move around (ex. Don't look down) this way if someone is watching you it is much harder to do you are constantly getting energy. 
How difficult do you think it would be to implement?
Not too hard.

**Comment by TheLazySquid** [comment]
This has now been added! Thanks for the suggestion.
