### ISSUE TITLE
New Gamemode Auto Answer

### ISSUE THREAD

**Issue by svnfxl** [TheLazySquid/GimkitCheat#38]
Hello, Would it be possible to add a auto anwer for the new gamemode, - Dont Look Down?

**Comment by TheLazySquid** [comment]
I believe auto answer already works for don't look down. I'll test this later, but I'm pretty sure it was working fine recently

**Comment by TheLazySquid** [comment]
Yep, it all works fine. If it still doesn't work for you feel free to follow up with browser information and/or error messages.
