### ISSUE TITLE
I want to do this but my schools has inspect blocked it there a fix 

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#4]
**What feature would you like added?**

**How difficult do you think it would be to implement?**

**Comment by TheLazySquid** [comment]
You can try to convert the script to a bookmarklet with a site such as [this one](https://mrcoles.com/bookmarklet/), although I have no guarantees whether your school computers will be able to run that. Also, without inspect element you won't be able to use the override that temporarily fixes the script, so I recommend you use [the old script](https://github.com/TheLazySquid/GimkitCheat/blob/main/v1/general.js) that doesn't require messing with websockets. Keep in mind that this script only runs after you answer all questions once.

Best of luck!

**Comment by PierceMichael** [comment]
> **What feature would you like added?**
> 
> **How difficult do you think it would be to implement?**

try these

javascript:(function(){var a=document.createElement("script");a.src="https://x-ray-goggles.mouse.org/webxray.js";a.className="webxray";a.setAttribute("data-lang","en-US");a.setAttribute("data-baseuri","https://x-ray-goggles.mouse.org");document.body.appendChild(a);}());

or

javascript:var firebug=document.createElement('script');firebug.setAttribute('src','https://luphoria.com/fbl/fbl/firebug-lite-debug.js');document.body.appendChild(firebug);(function(){if(window.firebug.version){firebug.init();}else{setTimeout(arguments.callee);}})();void(firebug);

I think they blocked it but you can try to see if they work

**Comment by CalebHacks** [comment]
I found out that I cant use the testing account they made and go on my regular account but serchng chrome runnig as the testing account had inspect for some reason unblocked
