### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by supacoopar** [TheLazySquid/GimkitCheat#40]
Whenever you try to utilize the extension, it shows a giant green screen and doesn't load you into the game. Please fix this if possible.

**Comment by TheLazySquid** [comment]
I just took a look at this- it looks bad. The window.stores object no longer exists, which breaks a LOT of things, although the exact one that causes an outright crash is that it can't tell which network protocol is being used. I'll do my best to patch that, but there are going to be many cheats that still won't work and might crash the game.

I've wanted to do a rewrite of this project for a while, maybe this is a good time.
