### ISSUE TITLE
The screen just goes green whenever cheat is used

### ISSUE THREAD

**Issue by pagedpenguin251** [TheLazySquid/GimkitCheat#47]
![Capture](https://github.com/TheLazySquid/GimkitCheat/assets/146399971/21f13ca2-2735-42f6-871b-2e1c679c5dc8)
The screen just goes green whenever cheat is used even on host and is unplayable.

**Comment by TheLazySquid** [comment]
Hey! Could you
a) Make sure the cheat is updated to the current version (0.4.1)
b) Tell me what browser you're using
c) Open the console (crtl+shift+I on most browsers) and send any errors?

**Comment by pagedpenguin251** [comment]
It worked after I uninstalled and reinstalled it.
