### ISSUE TITLE
bookmark does not work

### ISSUE THREAD

**Issue by C0mputa** [TheLazySquid/GimkitCheat#49]
my school blocks extensions and the bookmark dont work

**Comment by TheLazySquid** [comment]
This script doesn't have a bookmarklet, and because of the nature of the script I doubt one could be made without large amounts of changes to the code.

**Comment by TheLazySquid** [comment]
Update: The large amounts of changes to the code in question have been made, you can find an experimental bookmarlet version [here](https://github.com/TheLazySquid/GimkitCheat/blob/v4/build/bundle.bookmarklet.txt).
