### ISSUE TITLE
FISHTOPIA

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#5]
NOT WORKING

**Comment by RONAKPATELLLLLLL** [comment]
The fish a fish and sell a fish are not auto

**Comment by TheLazySquid** [comment]
There are issue templates for a reason, could you please give me some more context? Do you have the override set up? What version is it? Are there any errors in the console? What browser are you using? Just saying that it doesn't work can't really help me track down the issue (if there is one).

Thanks!

**Comment by PierceMichael** [comment]
> The fish a fish and sell a fish are not auto

So fishing and selling fish are not auto, is that what you're saying?
