### ISSUE TITLE
Make a bookmarklet version for mobile users

### ISSUE THREAD

**Issue by D0D4** [TheLazySquid/GimkitCheat#60]

**Comment by TheLazySquid** [comment]
No guarantees about whether it work on mobile, but if you can get bookmarklets working then try the normal bookmarklet [here](https://github.com/TheLazySquid/GimkitCheat/blob/main/build/bundle.bookmarklet.txt).

**Comment by CalebHacks** [comment]
The bookmarklet work I tested it
