### ISSUE TITLE
Weired green bug

### ISSUE THREAD

**Issue by caterk** [TheLazySquid/GimkitCheat#61]
When i join a game screen turns green, i use chrome, and i made sure everything is up to date. I uninstalled taper and re installed same with the script Pleas fix as i can no longer win in class without the auto answer lol

**Comment by TheLazySquid** [comment]
What gamemode are you trying to join, and is it an assignment? I can't figure out how to reproduce this. Also, what version of the script are you using? I know you said you made sure it's up to date but just to be sure lol

**Comment by helloIlovegimkit** [comment]
> When i join a game screen turns green, i use chrome, and i made sure everything is up to date. I uninstalled taper and re installed same with the script Pleas fix as i can no longer win in class without the auto answer lol



> What gamemode are you trying to join, and is it an assignment? I can't figure out how to reproduce this. Also, what version of the script are you using? I know you said you made sure it's up to date but just to be sure lol

It sometimes happens when you do custom games though for me the glitch has been fixed

**Comment by caterk** [comment]
I just tryed it again and now its black
![image](https://github.com/TheLazySquid/GimkitCheat/assets/98052666/58d15e3d-0ade-461e-87d6-8d85491e89c7)

**Comment by TheLazySquid** [comment]
Judging by the screenshot, you're using an old version of Gimkit Cheat or maybe have both the new and old one installed. Try updating/removing the old one.

**Comment by caterk** [comment]
how do I download the new one? that's the only one on greasyfork and I don't know how to import the one on github, can you update the one on greasyfork? Thanks!

**Comment by TheLazySquid** [comment]
All the ones on greasyfork are just people reuploading my code. In order to update this script, just click [this link](https://raw.githubusercontent.com/TheLazySquid/GimkitCheat/main/build/bundle.user.js).

**Comment by caterk** [comment]
Thank you! I'll try it right now
