### ISSUE TITLE
Jump Boost

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#63]
Since there is a speed up could you make a jump boost?

**Comment by TheLazySquid** [comment]
Unfortunately not, platformer physics don't have the same tolerance that 2D gamemodes have that makes speedup possible.

**Comment by helloIlovegimkit** [comment]
yk
platformer has this weird bug rn where you can super jump in dld or just any platformer :trollface: maybe there's something we can do to make it jump higher :trollface:

**Comment by CalebHacks** [comment]
That works ;) if if put in console

**Comment by CalebHacks** [comment]
I used this in only up and there's some places that you cant get to normally but you can with this

**Comment by TheLazySquid** [comment]
Alright, this has now been added along with a slider for jump heights. The code is a bit of a mess but I'm too lazy to fix it.
