### ISSUE TITLE
Jump boost glitch in gimkit????!!!⚠⚠⚠

### ISSUE THREAD

**Issue by helloIlovegimkit** [TheLazySquid/GimkitCheat#64]
yk
platformer has this weird bug rn where you can super jump in dld or just any platformer :trollface: maybe there's something we can do to make it jump higher :trollface:

**Comment by helloIlovegimkit** [comment]
rn I'm trying to code it and here's the progress on my findings
![image](https://github.com/TheLazySquid/GimkitCheat/assets/164534666/29fb4ce6-b1a5-4d5f-baf6-df64eae49d76)

**Comment by helloIlovegimkit** [comment]
rn I have it in overrides so it needs me to have the console open

**Comment by helloIlovegimkit** [comment]
@TheLazySquid

**Comment by TheLazySquid** [comment]
Gimkit's doing an April fool's event, which changed physics and disabled the anticheat. This likely won't work in the future.

**Comment by robloxsuckslikereallydude** [comment]
oh alr

**Comment by CalebHacks** [comment]
Could we make It think that its the april fool event?

**Comment by TheLazySquid** [comment]
No, the anticheat is server-side.

**Comment by helloIlovegimkit** [comment]
aw
