### ISSUE TITLE
Capture the Flag

### ISSUE THREAD

**Issue by CalebHacks** [TheLazySquid/GimkitCheat#7]
**What feature would you like added?** 
A script that I can capture the flag from anywhere 

**How difficult do you think it would be to implement?**
IDK

**Comment by TheLazySquid** [comment]
Unfortunately, there is some basic validation for picking up / capturing the flag, and you only can do that when in the normal pickup range.

**Comment by PierceMichael** [comment]
> Unfortunately, there is some basic validation for picking up / capturing the flag, and you only can do that when in the normal pickup range.

can you maybe extend the range?

**Comment by RONAKPATELLLLLLL** [comment]
or could you do so you can use invisisabits with the flag? Invisible with the flag

**Comment by TheLazySquid** [comment]
> or could you do so you can use invisisabits with the flag? Invisible with the flag or always invisible.

Unfortunately, you can't go invisible with the flag, even if you directly send the packet to the server. It still sends the "[player] went invisible!" in chat, but you are still very much visible to both teams.
