### ISSUE TITLE
this is the funniest sh*t ever

### ISSUE THREAD

**Issue by helloIlovegimkit** [TheLazySquid/GimkitCheat#74]
![image](https://github.com/TheLazySquid/GimkitCheat/assets/164534666/26fd17bb-139f-47e9-82d3-cdd321c2df10)

**Comment by helloIlovegimkit** [comment]
from ur script btw

**Comment by TheLazySquid** [comment]
I don't think you ever need to download the script, so the browser mistakenly flagging it as a virus doesn't really matter lol
