### ISSUE TITLE
Hacks Not Working While Hosting

### ISSUE THREAD

**Issue by IntelligenenceUnknownSH** [TheLazySquid/GimkitCheat#83]
The addon just doesn't work when hosting a game. I don't know much about coding, but I'm pretty sure it's just because the addon doesn't detect that https://gimkit.com/host is part of gimkit.com and so doesn't work.

P.S I know this can be fixed by joining the game as a separate player (this works even with one account), but this adds one more player, which then makes other people unable to join if it hits the cap. The cap for student accounts is 5 players and for educator accounts (you have to pay to have an educator account) is 30 players.

**Comment by TheLazySquid** [comment]
This is intentional, this script only works when joining a game.
