### ISSUE TITLE
Tampermonkey Solution

### ISSUE THREAD

**Issue by VillainsRule** [TheLazySquid/GimkitCheat#84]
For now, to comply with Chrome's latest "measures", TM is requiring users to turn on Developer Mode. There are three disadvantages to using Tampermonkey:

1. It's not open source.
2. It's realistically very slow.
3. It now wants to comply with Chrome.

Chrome extensions won't need to do this for another year, and Tampermonkey for some reason is doing it now. A large mod menu I contribute to recently moved to [ViolentMoney](https://violentmonkey.github.io), as it solves all these issues. I recommend you do that too, or at least make it an option.

**Comment by TheLazySquid** [comment]
ViolentMonkey looks a lot better! From some testing, everything seems to work seamlessly with it. Thanks for the suggestion!

**Comment by VillainsRule** [comment]
Though not implemented, I'll close as completed as it's on your radar.

**Comment by TheLazySquid** [comment]
What is there to implement other than recommending it in the README? The script seems to work without any problems.

**Comment by VillainsRule** [comment]
> What is there to implement other than recommending it in the README? The script seems to work without any problems.

my bad, hadn't seen there.
