### ISSUE TITLE
Bookmarklet Issue

### ISSUE THREAD

**Issue by Vedahini** [TheLazySquid/GimkitCheat#86]
![IMG_1568](https://github.com/user-attachments/assets/ec56fb28-2d6f-43d8-951b-c2243b009683)
After executing in bookmark, this page shows up, even if i do it before.

**Comment by CosmologyDunks** [comment]
Nothing even works for me anymore DOSENT do anything

**Comment by HiMyNameIsZeno** [comment]
> ![IMG_1568](https://private-user-images.githubusercontent.com/179182585/360711055-ec56fb28-2d6f-43d8-951b-c2243b009683.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjMzODEsIm5iZiI6MTcyNDQyMzA4MSwicGF0aCI6Ii8xNzkxODI1ODUvMzYwNzExMDU1LWVjNTZmYjI4LTJkNmYtNDNkOC05NTFiLWMyMjQzYjAwOTY4My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTQyNDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk4ZTQzMjAxMTYxNTgwMWViYzA5Y2Y1Y2Q2MzY0YTY5ZmVlZjc0NTM4NjY2ZGQ3Njg5MmY5MjRiOTQxMDVkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vGbpjE2SgtPMMWfjUYO2voQq2ehPoNctKU6c70SDnbc) After executing in bookmark, this page shows up, even if i do it before.

After replicating, I have a similar problem.

**Comment by TheLazySquid** [comment]
Same thing happened to me, it should be fixed now.
