### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [TheLazySquid/GimkitCheat#9]
**What feature would you like added?
Do the capture the flags cheats work in the tag game mode? If not that would be nice to have.
**How difficult do you think it would be to implement?**
IDK, not very hard?
Thanks!

**Comment by TheLazySquid** [comment]
There's now a basic script for tag available [here](https://github.com/TheLazySquid/GimkitCheat/blob/main/gamemodes/tag.js)! There's definitely more to come, as this one is pretty bare-bones.
