### ISSUE TITLE
Create a certain ctf cheat

### ISSUE THREAD

**Issue by HelloIloveGimkit2** [TheLazySquid/GimkitCheat#90]
basically what the cheat will do is it will freeze your character and then teleport you to the flag interact and capture it then it will unfreeze/thaw your character that way you get rubber banded back and since you got the flag and tp'ed from your spawn you would have the flag automatically be captured

more idiot friendly version: freeze your character, get the flag, unfreeze while at the enemies flag, and naturally you'll be tp'ed back with the flag and score a point.

**Comment by TheLazySquid** [comment]
Rubberbanding only happens on your end, you can't use it to do stuff like that.
