### ISSUE TITLE
Bookmarklet Not Detecting Game

### ISSUE THREAD

**Issue by HiMyNameIsZeno** [TheLazySquid/GimkitCheat#91]
There is no game detection currently. The cheats stay grayed out. (ex. if you are in Fishing Game, you cannot use any cheats related to that game, they will not allow you to click it.) Only cheats that work currently are the global cheats (ex. answer automatically and hide energy popup.)

**Comment by HiMyNameIsZeno** [comment]
This also seems to happen for the Tampermonkey script too.

**Comment by cakebill12** [comment]
i think its because gimkit got an better anticheat so most scripts are blocked

**Comment by TheLazySquid** [comment]
Nope, I just accidentally broke it while fixing other stuff. This should now be fixed.
